# Generated by Django 4.1.1 on 2022-09-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventuretravel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='items',
            new_name='name',
        ),
    ]
