# Generated by Django 4.1.1 on 2022-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventuretravel', '0002_rename_items_items_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='language',
        ),
        migrations.AddField(
            model_name='service',
            name='language',
            field=models.ManyToManyField(help_text='Seleccione los idiomas que maneja en las actividades.', to='adventuretravel.language'),
        ),
    ]
