# Generated by Django 4.1.1 on 2022-09-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventuretravel', '0005_alter_perfil_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='services_cover',
            field=models.ImageField(blank=True, null=True, upload_to='services_cover', verbose_name='Imagen'),
        ),
    ]
