# Generated by Django 4.1.1 on 2022-09-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventuretravel', '0007_category_service_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['activity', 'lender', 'category']},
        ),
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
