# Generated by Django 4.1.1 on 2022-09-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventuretravel', '0011_alter_category_options_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['activity', 'lender']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
